runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: routes.app

libraries:
- name: flask
  version: "0.12"
- name: ssl
  version: latest

  automatic_scaling:
    max_concurrent_requests: 30
    min_idle_instances: 0
    max_pending_latency: 25ms
